name: Create Release Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'LimitlessPhotos.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./LimitlessPhotos.zip
          name: LimitlessPhotos-zygisk.zip