name: Create Release Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code (relies on .gitattributes for line endings)
      - uses: actions/checkout@v4

      # Optional: Verify all files use LF endings
      - name: Verify LF line endings
        run: |
          if grep -rl $'\r' .; then
            echo "CRLF line endings found!"
            exit 1
          else
            echo "All files use LF line endings."
          fi

      # Read changelog for release notes
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      # Update GitHub Release description
      - name: Update Release Description
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Create zip archive using native zip with no compression (store only)
      - name: Archive Release
        run: |
          zip -0 -r LimitlessPhotos.zip . \
            -x '*.git*' '*.github*' '*node_modules*' '*.editorconfig' 'README.md' 'CHANGELOG.md'

      # Upload zip file to release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./LimitlessPhotos.zip
          asset_name: LimitlessPhotos.zip
          asset_content_type: application/zip