name: Create Release Archive

on:
  release:
    types: [created]

permissions:
  contents: write  # Needed to upload assets

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'LimitlessPhotos-zygisk.zip'
          exclusions: '*.git* *.github* /*node_modules/* .editorconfig'

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: LimitlessPhotos-zygisk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
