name: Create Release Archive

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Zip the project
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: LimitlessPhotos.zip
          exclusions: 'README.md *.git* *.github* /*node_modules/* .editorconfig'

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: LimitlessPhotos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
